sudo: false
language: java
cache:
  directories:
  - "$HOME/.m2"
jdk: oraclejdk8
env:
  matrix:
  - DISPLAY=:99.0
  global:
    secure: "tPRTksh9Jd9IEd0F+A2OsrPg5VpMdiR6g6aFMlCE/ELAnHDqrNi8nPn0LGq0zfM7H+9ZTSyRTBulQ24ox2l5olhCQb7yL0NU95r30oxJWZbRQ5CipV+ZW9N9gW4vPELmMOeYW68O4DEjwk+Di7RQbRBfOAcqBh/mGC1KWocFaiPLDeMBsZhHSL+fdhYPKRvrLS+bN+MWx2cyeV0dy+4P5vbqKvKomZvg6kz1gDS9nR3HZUcsdT7i+iXL0eqSQaG1ZC2oj9RMQliKaaJmnXbQItyln8jvm8dqra/LSis9CkdVaY97S+1fk2Sefzq7svWVdKTtimHJp6v1aydy/K0bpmzSZXaSiEVdBl9f3SrWVUWMOT8PozWTBJMTlS9qwCIL9HoL2zL77BJFWexIxOrETYwJt7nP/x3NxncMcYhnsx9ZkQYP2BKXOu3WDSBJ6XdgW/9+9YlQ7WpuzVeyqlO1w15nnk/GmivcaNrx7uiM1U64hRa8EdOyNWvMgJBsubL4+nOiPkoDwLrugUpFnwv+p8QkHuph6e+0tUlva28W3vVGnrMz7xlLNu3plGqv+zw1M26Sbgfbz1BUOkXDDnxoQJUuLEfvTQFo2XKqQWNlDmtEQv8FviOLtOUmb3Nbow871CSHXjiP/pvrkRlBCYPBGPFgFwdB0knscVmhhmRw35E="
addons:
  apt:
    packages:
    - metacity
before_install:
- export DISPLAY=:99.0
- "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile
  --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1920x1080x16"
- sleep 5
- metacity --sm-disable --replace 2> metacity.err &
script:
- mvn clean package
after_success:
- .travis/push.sh
