sudo: false
language: java
cache:
  directories:
  - "$HOME/.m2"
jdk: oraclejdk8
env:
  matrix:
  - DISPLAY=:99.0
  global:
    secure: "sgzv5nuMFcFv9c5v+Mm4hR1C0VQ5Ms39HTTayew5D9qivrasunPUnSpbOmjKME65dVv+IMtXwAqXfRoL8qBFnnaBWS0bDBp871a16QRyxNOb3Pa/8NHtYig//bqLIXbiFZwqeAW7mNJIPCTM6ADBR7Zzy9xU1IfHXrdxjcP7BIPMBoI/JDZuJsYqf3oD9+ld+zP2zMM2PfW7lNWdCmnAbqBj1Jzq2jNxGylqTMvoBkz5dWvUCYsuBQ3Y9y8FzAvkQHvVQ25CnVhXASGuGEtBHxFZkehQjYhpcY1b94cf76lGuPAAZk+kqlAyUJroLct0H2TayYvMFwqsJ9Sr4P1yRk/LfQnFh0Q09A61cICqoIKo82I3xcGS3/3U8tBaIhxxfrsS3Plhue0NyomrRnkT03f4beB4J8gPNVasPEZWHR8cj3Yc6Jm3jmzlAUTp8UgC75J++nkrTGHKGury7uIcpqwpw7+TLHfI6jqbzziuISY5HxYL8fiMUMxtqFflQb2/RiKjvwNCcgxKvMPtoQWrQN0a7Bmb0XxOkXG8belJkH9U6m7B23sWSWAVVfoReS3OqaoxcJqJ5ICSYFAISEnBnY/C7ZjDu3gj/aESrD81PcZYITuaQrm9gLnXZWBhDtTIDfDDdwBAfr73IKN+sxsQrLvzDcw45TAzBlRlGHSs0IY="
addons:
  apt:
    packages:
    - metacity
before_install:
- export DISPLAY=:99.0
- "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile
  --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1920x1080x16"
- sleep 5
- metacity --sm-disable --replace 2> metacity.err &
script:
- .travis/build.sh
