language: java

jdk: oraclejdk8

env: DISPLAY=:99.0

install: true

addons:
  apt:
    packages:
    - metacity

#before_install:
# - sudo apt-get update
# - sudo apt-get install metacity

before_script:
 - sh -e /etc/init.d/xvfb start
 - metacity --sm-disable --replace 2> metacity.err &